# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst

sudo: required
dist: trusty
language: cpp

os:
  - linux

compiler:
  - gcc


addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov

matrix:
    include:
      - bare_linux:
        env: ROS_DISTRO="none"
      - ros_indigo:
        env: ROS_DISTRO="indigo"
      - ros_kinetic:
        env: ROS_DISTRO="kinetic"
      - ros_melodic:
        env: ROS_DISTRO="melodic"
    fast_finish: false

before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq build-essential 
  - if [ "$ROS_DISTRO" = "none" ]; then sudo apt-get --reinstall install -qq libzmq3-dev; fi
  # GTest: see motivation here https://www.eriksmistad.no/getting-started-with-google-test-on-ubuntu/
  - sudo apt-get --reinstall install -qq libgtest-dev cmake
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd $TRAVIS_BUILD_DIR

install:
  - if [ "$ROS_DISTRO" != "none" ]; then git clone https://github.com/ros-industrial/industrial_ci.git .ci_config; fi

before_script:
  # Prepare build directory
  - mkdir -p build
  
script:
  - if [ "$ROS_DISTRO"  = "none" ]; then (cd build; cmake .. ; sudo cmake -DCMAKE_BUILD_TYPE=Debug -DADD_COVERAGE=ON --build . --target install; ./bin/behaviortree_cpp_test); fi
  - if [ "$ROS_DISTRO" != "none" ]; then (.ci_config/travis.sh); fi



after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  
env:
  global:
  - LANG="en_US.UTF-8"
    
notifications:
  email:
    recipients:
    - davide.faconti@gmail.com
    on_success: change
    on_failure: always  
